### ISSUE TITLE
Empty Content

### ISSUE THREAD

**Issue by FezodgeIII** [Coolfire74/Garrys-Mod-Addon-Test#1]
Sorry if I'm mistaken, but you're .lua files all seem to be empty. I'm not sure whever this is intentional or not, but it looks kinda bad, as it looks like you've created a repo, and then just left it, which is bad practice. If you have finished with this, you might want to delete it? Or you may have more content, and havn't uploaded it yet? I would like to know, thanks!

**Comment by Coolfire74** [comment]
I have created some of the code for the .lua files its just I need to fix some bugs before I commit it. Thanks for reminding me though.

**Comment by FezodgeIII** [comment]
No problem, I'll look forward to seeing it!
